--CREATION OF STUDENT DEATILS
CREATE TABLE LSTUDENT_DETAILS (ID INT,NAME VARCHAR(10),MOBILE BIGINT,EMAIL VARCHAR(30))
INSERT INTO  LSTUDENT_DETAILS VALUES(101,'SAI',7893570611,'saivardhan@gmail.com')
INSERT INTO  LSTUDENT_DETAILS VALUES(102,'VARDHAN',9959180347,'saivardhan2408@gmail.com')
INSERT INTO  LSTUDENT_DETAILS VALUES(103,'GOPI',6302299809,'gopikrishna@gmail.com')
INSERT INTO  LSTUDENT_DETAILS VALUES(104,'VENKAT',9441524315,'venkat@gmail.com')
UPDATE LSTUDENT_DETAILS SET EMAIL = 'saivardhan' WHERE ID = 101
UPDATE LSTUDENT_DETAILS SET EMAIL = 'saivardhan2408' WHERE ID = 102
UPDATE LSTUDENT_DETAILS SET EMAIL = 'gopikrishna' WHERE ID = 103
UPDATE LSTUDENT_DETAILS SET EMAIL = 'venkat@gmail' WHERE ID = 104

SELECT * FROM LSTUDENT_DETAILS

--CREATION OF BOOK DETAILS
CREATE TABLE LBOOK_DETAILS(BID INT,BNAME VARCHAR(30),AUTHOR VARCHAR(30))
INSERT INTO LBOOK_DETAILS VALUES(201,'CLEAN CODE','ROBORT')
INSERT INTO LBOOK_DETAILS VALUES(202,'CODE COMPLETE','STEVE MCCONNELL')
INSERT INTO LBOOK_DETAILS VALUES(203,'CODE','CHARLES PETZOLD')

SELECT * FROM LBOOK_DETAILS

--CREATION OF BOOK ISSUE TABLE
	CREATE TABLE LBOOK_ISSUE_DETAILS(STUDENTID INT,BOOKID INT,BOOK_NAME VARCHAR(30)) 
	ALTER TABLE LBOOK_ISSUE_DETAILS ALTER COLUMN BOOK_NAME VARCHAR(50)
	SP_RENAME 'LBOOK_ISSUE_DETAILS.BOOK_NAME','S_EMAIL'



SELECT EMAIL FROM LSTUDENT_DETAILS WHERE ID = 102
--CREATING PROCEDURE TO ENTER DETAILS INTO BOOK_ISSUE_TABLE

SELECT * FROM LBOOK_ISSUE_DETAILS

DROP TABLE LBOOK_ISSUE_DETAILS

CREATE TABLE STUDENTQ(STID INT,SNAME VARCHAR(20),SMALLID VARCHAR(20),COURSEID INT)

INSERT STUDENTQ VALUES(101,'ADAMS','ADD@GMAIL.COM',10),(102,'JAMES','JAY@GMAIL.COM',20),(103,'SCOTT','SCOT@YAHOO',30)

CREATE TABLE COURSEQ(COURSEID INT,CNAME VARCHAR(20),CFEE DECIMAL(6,2))

INSERT COURSEQ VALUES(10,'SQL SERVER',1200),(20,'SQL DBA',1500),(40,'MSQL',3200),(50,'SAP',2400)

SELECT * FROM STUDENTQ

SELECT *FROM COURSEQ

SELECT * FROM STUDENTQ CROSS JOIN COURSEQ

SELECT * FROM STUDENTQ S LEFT OUTER JOIN COURSEQ C ON S.COURSEID = C.COURSEID

SELECT * FROM STUDENTQ S RIGHT OUTER JOIN COURSEQ C ON S.COURSEID = C.COURSEID

SELECT * FROM STUDENT S FULL OUTER JOIN COURSE C ON S.COURSEID = C.COURSEID

SELECT * FROM STUDENTQ INNER JOIN COURSEQ ON STUDENT.COURSEID = COURSE.COURSEID

CREATE TABLE EMDETAILS (EID INT,ENAME VARCHAR(20),ESAL INT,AGE INT)
INSERT EMDETAILS VALUES (101,'AA',10000,20),(102,'BB',10000,21),(103,'CC',20000,23),(104,'DD',23000,24)
SELECT * FROM EMDETAILS

SELECT E1.EID,E1.ENAME,E1.ESAL FROM EMDETAILS E1, EMDETAILS E2 WHERE E1.ESAL = E2.ESAL AND E2.ENAME = 'AA'